const actions = {
  CONNECT_TO_ETHEREUM_NETWORK: "todoList/CONNECT_TO_ETHEREUM_NETWORK",
  LOADING_APPLICATION: "todoList/LOADING_APPLICATION",
  LOAD_TODO_LIST: "todoList/LOAD_TODO_LIST",
  ADD_TASK: "todoList/ADD_TASK",
  COMPLETED_TOGGLE: "todoList/COMPLETED_TOGGLE",
};

export default actions;
